"""first revision

迁移 ID: 4b2981ef169e
父迁移:
创建时间: 2025-07-25 13:56:07.758475

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4b2981ef169e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nonebot_plugin_echo",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_echo_chatblacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("keywords", sa.Text(), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("ban_scene_id", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_nonebot_plugin_echo_chatblacklist")
        ),
        info={"bind_key": "nonebot_plugin_echo"},
    )
    op.create_table(
        "nonebot_plugin_echo_chatcontext",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("keywords", sa.Text(), nullable=False),
        sa.Column("time", sa.BigInteger(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_echo_chatcontext")),
        info={"bind_key": "nonebot_plugin_echo"},
    )
    op.create_table(
        "nonebot_plugin_echo_chatanswer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("keywords", sa.Text(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("time", sa.BigInteger(), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["nonebot_plugin_echo_chatcontext.id"],
            name=op.f(
                "fk_nonebot_plugin_echo_chatanswer_context_id_nonebot_plugin_echo_chatcontext"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_echo_chatanswer")),
        info={"bind_key": "nonebot_plugin_echo"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_echo_chatanswer")
    op.drop_table("nonebot_plugin_echo_chatcontext")
    op.drop_table("nonebot_plugin_echo_chatblacklist")
    # ### end Alembic commands ###
